Decoupled healthcheck from DB node, added --verify function
yugabyte/yb-tools pull request #100
Opened 2023-11-20 22:58 UTC by mlaspina

Decoupled healthcheck from DB node, added --verify function

2023-11-21 00:21 UTC, na6vj requested changes

2023-11-21 00:21 UTC, na6vj commented on yb_os_maint/yb_os_maint.py
> +    master = node['cloudInfo']['private_ip'] + ':' + str(node['masterHttpPort'])  + '/api/v1/health-check'
Suggest using a name like 'master_health_check_URI' rather than just 'master'

2023-11-21 00:21 UTC, na6vj commented on yb_os_maint/yb_os_maint.py
> +        if node['isTserver']:
Master & tserver logic is identical  - should use a subroutine w params

2023-11-21 00:21 UTC, na6vj commented on yb_os_maint/yb_os_maint.py
> +        if node is not None:
This should call the 'verify' subroutine, instead of repeating that logic here..

2023-11-21 16:59 UTC, mlaspina commented on yb_os_maint/readme.md
> +  -v, --verify          Verify Master and tServer process are in correct state per universe config
Requested by Wells to ensure tserver/master on node is in same state as YBA

2023-11-22 16:08 UTC, na6vj approved these changes

2023-11-22 16:08 UTC, merged